name: CI # name of the workflow


on: [push] # Events on which the workflow will

# workflow must have atleast one job
jobs:
  build: # job name
    runs-on: ubuntu-latest  # type of machine on which workflow runs (runner)
    steps:
    - uses: actions/checkout@v1
    - name:  Run a one liner Script
      run: echo "hello world"
    - name: Runa  multi-line script
      run: |
        echo "build"
        echo "Run Integration Test"
        echo "Deploy"
    - name: Runa  multi-line script
      run: |
        echo "build"
        echo "Run Integration Test"
        echo "Deploy"
