name: challenge
on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: print date ubuntu-latest
        run: date
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: print date windows-latest
        run: "Get-Date"
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
      - name: print date on macos-latest
        run: date

  job4:
    name: Fourth job
    runs-on: ubuntu-latest
    needs: [job1,job2,job3]
    steps:
      - name: print  completed
        run: echo "All Jobs Completed"

    
  